### ISSUE TITLE
CLDR data is reported as missing when locale is set with a region

### ISSUE THREAD

**Issue by arbrown** [jquery/globalize#357]
When I try to use Globalize with a language-region combo (like en-US,) it always gives me the error: 
    `Error: E_MISSING_CLDR: Missing required CLDR content 'main/en/dates/calendars/gregorian/dateTimeFormats/short'.`

The basic code is as follows:

    Globalize.load(
    {
      "main": {
        "en-US": {
	    ... // content omitted
      }
    }
    });
    Globalize.locale('en-US');
    var formatter = Globalize.dateFormatter({datetime: 'short'});

At that point, globalize always throws the error.  However, if I provide it with CLDR data that is not region-dependent (like just plain 'en') and set my locale to the same, the code works.  In both cases, it is looking for cldr data that is just under the language code (ignoring the region for the cldr path.)  I have tested de-DE, and pt-BR and see the same results in those languages: it only looks for the language cldr data, ignoring the language-REGION data that was provided.

I saw an [issue](https://github.com/rxaviers/cldrjs/issues/17#issuecomment-48643041) on cldrjs that implied that the issue could be solved by using just en instead of en-US (which I am doing as a stopgap) but this same issue occurs for any region specific locale, and just using the language won't always be the right thing to do.

I'm not sure if this issue is better here or on cldrjs.  Let me know if I need to move it, or provide more information.

**Comment by michael-fischer** [comment]
@rxaviers,  It doesn't look like you got any more answers on [rxaviers/cldrjs#17](https://github.com/rxaviers/cldrjs/issues/17#issuecomment-48643041) so I thought I would weigh in with thoughts about a particular use case.  

If Globalize is going to be within a web page there is a high likely-hood that the browser settings may be considered for which language to load.  This will most likely come in as a two part locale (i.e. en-US or es-BO).  At least, it seems that way in the browsers I have checked.  It seems odd to me that if the browser is set to "en-US" that I would have to use ` var globalize = Globalize("en").` and likewise key the JSON data off of "en."  It is most natural to assume that "en-US" would be used.  This nuance of CLDR is not something that the consumer of Globalize should need to know.  

Especially since the browser locale settings have to be provided dynamically through server side processing of the request variables. Right now, since all of my data is stored based on culture, I have to manually tweak both the server side and client side to adapt for this [perceived] idiosyncrasy.I already felt bad coercing some locales into another (i.e. any two part locale that wasn't es-ES into es-419) but I could attribute that to a domain decision and isolate it to the business logic layer on the server.  It's use being completely transparent on the client [unless someone was purposely abusing the system].  

Let me know which way you think you are going to go [or if I am completely out in left field].  Thanks.

Totally irrelevant side note.  At least in my use case en-US is not the exception.  All of the languages we are trying to support use the root with the exception of en-GB.

**Comment by rxaviers** [comment]
@michael-fischer, your thoughts and contributions are welcome.

On regard of rxaviers/cldrjs#17, although the issue is indeed quiet, lot has happened on cldr-users mailing list. So, I've just updated the issue accordingly and I'm still waiting for a couple of more answers there.

On regard of your proposal,

> if the browser is set to "en-US" that I would have to use `var globalize = Globalize("en")`.

You don't. You can use `var globalize = Globalize( "en-US" )` just fine. What happens is that `Globalize( "en-US" )` or `Globalize( "en" )` or `Globalize( "en-Latn-US" )` all will look for the **en** bundle (according to `globalize.cldr.attributes.languageId`). To give another example both `Globalize( "en-GB" )` or `Globalize( "en-Latn-GB" )` will look for the **en-GB** bundle. Note this is how it works now and it may eventually change after rxaviers/cldrjs#17 is closed.

Before going too deep here, what's your use case? I understood your client-side detects the user's browser locale and then fetches the needed CLDR data dynamically on your server. Is that the case? I also assume your problem is that you're willing to fetch `"cldr/main/en-US/ca-gregorian.json"` instead of `"cldr/main/" + globalize.cldr.attributes.languageId + "/ca-gregorian.json"`. Is that correct? If so, I understand your pain. Otherwise, please could you clarify?

> Totally irrelevant side note. At least in my use case en-US is not the exception. All of the languages we are trying to support use the root with the exception of en-GB.

Please, could you clarify?

**Comment by michael-fischer** [comment]
@rxaviers,

Short version:
I guess my thought boils down to that if you use the Language-Region your message table still needs to be keyed of the language  So even if you use .`Globalize( "de-DE" )` you still need to have the language in your json.

Longer version:

> You don't. You can use var globalize = Globalize( "de-DE" ) just fine.

I concede this point as using the Language subtag was my way of working around the problem that I was really trying to solve.  Namely, the disconnect between using Language-Region when calling LoadMesssage.  I assume internally `globalize.cldr.attributes.languageId` is used so the loaded JSON can't use Language-Region.  Or at least I have only had success with:

```json
{
    "root": {
        "actions": "Actions",
        "activityNotes": "Activity Notes",
		...
    },
    "de": {
        "actions": "Aktionen",
        "activityNotes": "Aktivitätshinweise",
		...
    }
}
```
as opposed to 
```json
{
    "root": {
        "actions": "Actions",
        "activityNotes": "Activity Notes",
		...
    },
    "de-DE": {
        "actions": "Aktionen",
        "activityNotes": "Aktivitätshinweise",
		...
    }
}
```

Note, I changed your example to "de-DE" from "en-US" since en-US gets loaded into "root" as a fallback and therefore just works.    

>Before going too deep here, what's your use case? I understood your client-side detects the user's browser locale and then fetches the needed CLDR data dynamically on your server. Is that the case? I also assume your problem is that you're willing to fetch "cldr/main/en-US/ca-gregorian.json" instead of "cldr/main/" + globalize.cldr.attributes.languageId + "/ca-gregorian.json". Is that correct? If so, I understand your pain. Otherwise, please could you clarify?

My use case is slightly more complicated that than but we can boil it down we use the browsers locale.  I actually build what to download using a string similar to that.  I just don't get the value from the `globalize.cldr.attributes.languageId`.  However, doesn't your example have a chicken before the egg problem?  Is it possible to initialize globalize prior to fetching the CLDR data?   However, I could do something like the following demo code:

```javascript
                var culture = "es-ES";   // hard coded for example only.
                var globalize = Globalize(culture);
                var language = globalize.cldr.attributes.languageId;
 
                var jsonData = $.ajax({
                    url: "json/DB2-" + culture + ".json",
                    async: false,
                    cache: false,
                    dataType: 'json'
                }).responseText;

                var strings = JSON.parse(jsonData);
                
                // Hack the language key here.
                if (strings.hasOwnProperty(culture) && language !== culture) {
                    strings[language] = strings[culture];
                    delete strings[culture];
                }

            Globalize.loadMessages(strings);
```

This would make the hack local to the client where it details with CLDR and not something sprinkled through the system.  Still something that I shouldn't need to do but an acceptable workaround.

**Comment by rxaviers** [comment]
@michael-fischer questions: https://gist.github.com/rxaviers/fd36f8fa699e81ca82b7

**Comment by srl295** [comment]
@rxaviers still not sure I follow the issue re: CLDR data. Perhaps we should chat sometime.

**Comment by rxaviers** [comment]
Sure, I've sent you an email.

**Comment by gkindel** [comment]
Also following this and the conversation over on CLDR.js --am wondering if this approach (which works) is a terrible idea. 
```javascript
    Globalize.load({
        "supplemental": {
            "likelySubtags": {
                "en": "en-Zzzz-US",
                "en-GB": "en-Latn-GB",
                "en-US": "en-Latn-US"
            }
        }
    });

    Globalize.loadMessages({
        "en": {
            hello: "Hello",
            world : "world"
        },
        "en-US": {
            hello : "'Sup"
        },
        "en-GB": {
            hello: "Cheerio"
        });

Globalize('en').messageFormatter("hello")()  //  "Hello"
Globalize('en').messageFormatter("world")()  //  "world"

Globalize('en-US').messageFormatter("hello")()  //  "'Sup"
Globalize('en').messageFormatter("world")()  //  "world"

Globalize('en-US').messageFormatter("hello")()  //  "Cheerio"
Globalize('en').messageFormatter("world")()  //  "world"

```

Note: requires cldr/unresolved.js.

**Comment by rxaviers** [comment]
:joy: You're hacking the likelySubtags... Good job, but you cannot use Zzzz or ZZ as subtags in its entries (as far as I know). Although, this is irrelevant and you could use (for example) `"en": "en-Latn-FR"` and your example would be valid and work just fine for your case. Note likelySubtags informs Globalize which locales have default content [1]. Default content means that the child content is all in the parent. For example, en's default content is en-Latn-US (unless "hacked"), it means en-Latn-US (or en-US) must inheriting everything from en. But, in case you want to tell Globalize that en's default content is actually en-Latn-FR (France), Globalize will expect different data in en-US and therefore will use that different messages.

Summary, if you know what you're doing go ahead. But, I'd first ask myself why my application really needs a different message for en-US than en. All en-US messages should be in en. Other English spoken countries (e.g. en-GB) should specify the overriding messages. (again, unless you really know what're doing.)

1: "The likelySubtag supplemental data provides default information" ([ref](http://www.unicode.org/cldr/charts/latest/supplemental/likely_subtags.html)).

**Comment by rxaviers** [comment]
Update... So far the most appealing solution for this issue (and https://github.com/rxaviers/cldrjs/issues/17) is the "A simple & bulletproof solution for bundle lookup" described in [Bundle Lookup thoughts](https://docs.google.com/document/d/1qLbuz659VvCVhgyd08KRP0SMuqCvK9bSS3-0W-kMuuw/edit?usp=sharing), which basically is  @scottgonzalez's [2nd approach](https://github.com/jquery/globalize/issues/357#issuecomment-66116374). Although, it's still not final and conversation is still going on.

**Comment by gkindel** [comment]
I redacted my earlier comment because I realized it was silly, but have gotten along using parentLocales. My main goal was to have my en-US strings actually labelled as such.  Who knows, maybe population data will change and some other culture will become dominant 'en'.  I don't like the fact that my strings file HAS to coordinate with the likelySubtatgs file.   With the below solution "en" and "en-GB" inherit from "en-US".

```javascript
    Globalize.load({
        "supplemental": {
            "parentLocales": {
                "parentLocale": {
                    "en" : "en-US"
                }
            },
            "likelySubtags": {
                "de": "de",
                "en": "en",
                "fr": "fr"
            }
        }
    });

    Globalize.loadMessages({
        "en-US": {
            hello : "'Sup",
            world : "world"
        },
        "en-GB": {
            hello: "Cheerio"
        },
        "fr": {
            hello: "Bonjour",
            world : "tout le monde"
        },
        "de": {
            hello: "Guten Tag",
            world : "welt"
        }
    });
```

**Comment by rxaviers** [comment]
@gkindel this is wrong. Feel free to ping on [IRC](http://irc.jquery.org/) if you'd like to chat about it.

**Comment by gkindel** [comment]
"Wrong" is pretty severe and nonspecific. I realize this is still alpha and I'm muddling along with the documentation that is available, and will look for any updates.  And of course I appreciate the tremendous amount of effort you are all putting into an open source cause.   I don't expect hand holding, but I can surface up some end-user confusion on these manners.  A link to docs, further reading, or keywords to google would be helpful.

As an end user, I don't actually understand why likelySubtags is a hard dependency at all, or why it forces a less specific naming convention for my messages JSON.  My impression was that it exists to resolve ambiguity, not introduce it.   Seems that it should do nothing for the message formatter if i set a locale of "en-US", but should step in and help with a locale of "en" or "en-foo".  

The code may be hacked, but it works to allow me to specify 'en-US' strings. and have them be accessible via 'en-US' or 'en' without throwing an error, which seemed to match the problem the @arbrown was having.

**Comment by rxaviers** [comment]
@gkindel, the data you used for likelySubtags and parentLocales are wrong. It may work for your specific example. But, it will generate other problems. Because, they are wrong. More info about likelySubtags or parentLocales can be found here respectively: http://www.unicode.org/reports/tr35/tr35.html#Likely_Subtags and http://www.unicode.org/reports/tr35/tr35.html#Parent_Locales.

Having said that, you're very welcome to help and thanks for your comments so far. But, the solution for this issue is going in this path: https://docs.google.com/document/d/1qZwEVb4kfODi2TK5f4x15FYWj5rJRijXmSIg5m6OH8s/edit and https://docs.google.com/document/d/1qLbuz659VvCVhgyd08KRP0SMuqCvK9bSS3-0W-kMuuw/edit#heading=h.irqx9cg2caef

**Comment by rxaviers** [comment]
Hello everyone,

https://github.com/rxaviers/cldrjs/pull/26 is being considered as a solution to this issue. More details and examples can be found at https://github.com/rxaviers/cldrjs/blob/fix-17/doc/bundle_lookup_matcher.md.

Feel free to review it and add your comments. I would very much appreciate your feedback.

---

In other words, the original example of this issue will work just fine.

    Globalize.load(
    {
      "main": {
        "en-US": {
	    ... // content omitted
      }
    }
    });
    Globalize.locale('en-US');
    var formatter = Globalize.dateFormatter({datetime: 'short'});

The same is also valid for messages. For example:

```javascript
Globalize.loadMessages({
    "en-US": {
        hello : "'Sup"
    }
});

Globalize( "en-US" ).formatMessage( "hello" ); // Sup
```

PS: @gkindel has added a comment about formatting messages and using inheritance, which currently works and is still going to work after this fix. What is wrong in his example is that he is using different data in `en` (default content for `en-US`) and `en-US`, which is fundamentally wrong. This particular problem could be discussed via [IRC](http://irc.jquery.org/) or by creating a separate issue.

**Comment by michael-fischer** [comment]
@rxaviers, this is good to know. Thank you.  I still think that it seems odd that loading en and en-US would change the bundle ID of en-US but hopefully that won't happen much and won't cause consternation moving forward.

**Comment by rxaviers** [comment]
Great.

> I still think that it seems odd that loading en and en-US would change the bundle ID of en-US.

Can you think of any problem this could cause?

**Comment by rxaviers** [comment]
I've created PR #384 to address this issue. The interesting unit test is [this one](https://github.com/jquery/globalize/pull/384/files#diff-023537a1eb6e158db4d12a1fe86f1128R48). It tests all cases listed as problematic by Mark Davis' [Fixing Inheritance document](https://docs.google.com/document/d/1qZwEVb4kfODi2TK5f4x15FYWj5rJRijXmSIg5m6OH8s/edit) and all cases listed here. All of them pass.

**Comment by Legends** [comment]
I've added the following globalization script:

  ```
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

    <!-- cldr scripts (needed for globalize) -->
    <script src="~/lib/globalize/cldr.js"></script>
    <script src="~/lib/globalize/event.js"></script>
    <script src="~/lib/globalize/supplemental.js"></script>

    <!-- globalize scripts -->
    <script src="~/lib/globalize/globalize.js"></script>
    <script src="~/lib/globalize/number.js"></script>
    <script src="~/lib/globalize/date.js"></script>

    <script src="~/lib/globalize/jquery.validate.globalize.js"></script>
```

I am also using `jquery.validate.unobtrusive`.

When I hit the submit button now after adding all the scripts after the `jquery.validate.unobtrusive` script, the form gets submitted to the server without validation to take place!

Then I thought perhaps I should call `Globalize.locale("de-DE")` but then I get:

> globalize.js:194 Uncaught Error: E_MISSING_CLDR: Missing required CLDR content `supplemental/likelySubtags`

Isn't `supplemental/likelySubtags` part of `cldr.js`?

Do I have to make some special api calls to initialize the whole thing correctly?

Thanks in advance!
