### ISSUE TITLE
Incorrect decimal rounding by Globalize.format()

### ISSUE THREAD

**Issue by stonys** [jquery/globalize#376]
Hi,

I see that formatNumber function uses multiplication of the float by some power of 10 to round decimals. It works, except sometimes a decimal of 5 is rounded down instead of up. For example: 
Globalize.format(0.00015, "n4") // Returns 0.0001, should return 0.0002.
Globalize.format(1.00015, "n4") // Return 1.0002 correctly.

A better solution would be to use numbers represented in exponential notation:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round

Cheers!

**Comment by rxaviers** [comment]
Hi @stonys, thanks for filing this issue and for your suggestion.

Note your example suggests you're using Globalize 0.x, which is no longer supported. Although, on Globalize 1.x, which we do support and whose equivalent example would be [1], it still returns `0.0001`.

Indeed parsing exponential notation strings is an interesting approach to avoid inaccurate floating point arithmetics. What makes using it a little trickier for us is that we also support arbitrary rounding increments (see [UTS#35 numbers](http://www.unicode.org/reports/tr35/tr35-numbers.html#Rounding)), i.e., rounding to increments different than powers of 10 only (e.g., [2]).

Rounding a decimal number on JavaScript is a three step process: shifting, rounding and shifting back. The difference between the current and proposed approaches are below.

| | Shift | Round | Unshift |
| --- | --- | --- | --- |
| Multiply/Divide | `0.00015*10000 = 1.4999999999999998` | `1` | `0.0001` |
| Parse exp notation strings | `+"0.00015e4" = 1.5` | `2` | `0.0002` |

So, in order to fix this issue while still using the Multiply/Divide approach, we should include a `.toFixed( 1 )` before rounding.

```diff
- round( ( value / increment ) ) * increment;
+ round( ( value / increment ).toFixed( 1 ) ) * increment;
```

| | Shift | Round | Unshift |
| --- | --- | --- | --- |
| Fixed Multiply/Divide | `( 0.00015*10000 ).toFixed( 1 ) = 1.5` | `2` | `0.0002` |

Thanks

---

1:
```javascript
Globalize( "en" ).formatNumber( 0.00015, { maximumFractionDigits: 4 } );
```

2: Rounding powers of 10.

```javascript
// 0.1
Globalize( "en" ).formatNumber( 0.6666, { maximumFractionDigits: 1 } ); // "0.7"

// 0.01
Globalize( "en" ).formatNumber( 0.6666, { maximumFractionDigits: 2 } ); // "0.67"
```

Rounding to different increments.

```javascript
//  0.5
Globalize.formatNumber( 0.6666, { pattern: "0.5" } ); // "0.5"

// 0.05
Globalize.formatNumber( 0.6666, { pattern: "0.05" } ); // "0.65"
```

**Comment by rxaviers** [comment]
My `.toFixed()` suggestion above will break roundings like "ceil 0.12300001". So, please ignore it.

The approach suggested by @stonys is still better than what I have suggested and what we currently have. I'm wondering if we can modify it in order to include different increments (like showen above). It seems https://gist.github.com/rxaviers/599b1888375894f8487d will do it. Needs better review.

**Comment by jzaefferer** [comment]
If you create an actual PR, I'll be happy to help with a review. gists don't have notifications etc. pp.

**Comment by rxaviers** [comment]
#386 implements a fix for this issue as suggested by @stonys.
