### ISSUE TITLE
Use native Ecma-402 for improved date and number formatting performance?

### ISSUE THREAD

**Issue by rxaviers** [jquery/globalize#399]
**Goal/Question**

Globalize doesn't use native Ecma-402 yet, which could potentially improve date and number formatting performance. Can we use it?

**General thoughts**

- Cross compatibility - Considering an environment supports Intl (see [Detecting the Internationalization API](http://norbertlindenberg.com/2012/12/ecmascript-internationalization-api/index.html)). Can we assume we can use it reliably in all our supported browsers/environments? We need to ensure (a) the functionality and (b) the locale coverage is reliable.
- What to do in cases where we need a feature not supported by Ecma? For example, using `round` option when formatting numbers. See also https://github.com/jquery/globalize/issues/328

[slide 25]: http://jsi18n.com/jsi18n.pdf

**Comment by rxaviers** [comment]
Usually, Globalize date and number modules are used as an alternative to Ecma-402. So, I don't suggest using Ecma-402 under the hoods for these methods.

Having said that, nothing holds people from using Ecma-402 along with Globalize though for its other modules. For example, one should be able to use Globalize message formatter, relative time formatter, unit formatter, etc with Ecma-402 Number and Date formatters. See #532

**Comment by ray007** [comment]
While `Globalize.numberFormat()` and `Intl.NumberFormat` provide similar functionality and are therefore mostly interchangeable (see proof of concept in my [cldr-intl-js](https://github.com/ray007/cldr-intl-js) repository), the same cannot be said for the date formatting.

`Intl.DateTimeFormat`
- has no support for patterns
- can not be used to simulate all ICU/CLDR pattern formatters without extra help

I did look through the date formatter code to maybe find a place to use my own formatters using `Intl.DateTimeFormat` instead, could use some pointers for this if possible...

The `Intl` object in the browser (and I assume node.js too) has almost all information needed, with some help it should be possible to generate the CLDR data with very little of the original CLDR data.
Add in some differential encoding for languages belonging to a family, and the amount of data one needs to load should be reduced substantially.

And by using the `Intl` object, you'd also get support for other calendars...
Plus improved performance I guess.

**Comment by rxaviers** [comment]
@ray007 I didn't follow your suggestion? Please, could you clarify.

**Comment by ray007** [comment]
Clarification?

I think using the `Intl` objects behind the scene would be a good idea. Especially since new `node.js` versions also have `Intl` support.
I would hope for improved performance, added support for non-gregorian calendars, and with some preparation a substantially reduced amount of data to load from your CLDR repo.

That the answer you were looking for?

**Comment by rxaviers** [comment]
Yes, that clarifies thanks. Is my [answer above](https://github.com/globalizejs/globalize/issues/399#issuecomment-147129784) clear to you? Basically, I explain such relationship and why it doesn't make sense to use Intl inside Globalize.

**Comment by rxaviers** [comment]
Having said that, your help is always welcome.

**Comment by ray007** [comment]
The long-team goal here at work is to get full ICU pattern support for all locales and calendars.
But it's getting bumped to at least the next release, we'll see.

What would help me, would be a list of CLDR data keys you use/need for globalize number/date format.
Because step 1 will be to reduce the amount of data needed to load for cldr as much as possible...

Step 2 will be using native `Intl.DateTimeFormat` formatters. I've already got a format function generator for most patterns, but it's ugly and needs a cleanup before it's usable outside our product...

**Comment by rxaviers** [comment]
> Because step 1 will be to reduce the amount of data needed to load for cldr as much as possible...

You can grep all `cldr.main` calls inside [date](https://github.com/globalizejs/globalize/tree/master/src/date) and [number](https://github.com/globalizejs/globalize/tree/master/src/number), but what really matters to significantly reduce the amount of data needed is to take into considerations the styles/formats you are actually using. For that, see https://github.com/globalizejs/globalize-compiler.

> Step 2 will be using native Intl.DateTimeFormat formatters. I've already got a format function generator for most patterns, but it's ugly and needs a cleanup before it's usable outside our product...

This has little relationship with step 1, I'm pretty confused about your goal.

Anyway, this isn't an issue, please follow up in stack overflow. Feel free to post the link here after you create one.

Thanks

**Comment by ray007** [comment]
ad 1) thanks, will do. But I cannot reduce the data beforehand since the selection calendar/locale/formats depends on the project the customer configures.

ad 2) while I think it will also be good for performance, it also seems the one reasonable way to support the other calendars without re-implementing a lot of icu stuff in javascript...
