### ISSUE TITLE
Issues with dateFormatter docs

### ISSUE THREAD

**Issue by jzaefferer** [jquery/globalize#422]
There's several issues with https://github.com/jquery/globalize/blob/0eebc186c426c59f7b0376dfbdcbf1ec4caacbf1/doc/api/date/date-formatter.md (noticed while reviewing #417)

* [x] The default argument is named "pattern", the Parameters section also says "pattern", but then describes it as a skeleton. Should rename the argument to "skeleton" to reflect its value, if that is indeed correct
* [x] The description for skeleton, a little bit further down, says "String value indicating a skeleton (see description above)", but there's actually very little description above. The key is the "date field" link (link text should be improved) that points at the UTS#35 docs for the skeleton fields. We should have a bit more information of our own, since the external doc is rather overwhelming.
* [x] `pattern` is warned against - maybe we should reflect that in the name, e.g. rename to `rawPattern`? Or `machinePattern` to indicate that its not for human consumption? If yes, should create a separate issue for that
* [x] Missing linebreak after "date" option - the others all have their description on a separate line
* [x] "Their possible values are: full, long, medium, or short." - replace the "or" with "and"
* [x] For the last section, "For improved performance on iterations"
  * Does that really belong here? Seems like something that the `formatDate()` method should mention/warn about.
  * If we keep this, make it executable: Replace or define `a` and `b` variables, replace or remove the `...`, do something with the formatted array.

**Comment by rxaviers** [comment]
Hi Jörn, thanks for raising all these points. Some questions...

> * The default argument is named "pattern", the Parameters section also says "pattern", but then describes it as a skeleton. Should rename the argument to "skeleton" to reflect its value, if that is indeed correct

The first argument is not "skeleton". But, it can be.

The first argument can be either a skeleton, any preset (date, time, or datetime), or a raw pattern. The name `pattern` should reflect it. I'm sure there's a better name for this argument. Any ideas?

> * The description for skeleton, a little bit further down, says "String value indicating a skeleton (see description above)", but there's actually very little description above. The key is the "date field" link (link text should be improved) that points at the UTS#35 docs for the skeleton fields. We should have a bit more information of our own, since the external doc is rather overwhelming.

Is the very little description you are referring to the "Skeleton provides a more flexible formatting mechanism than the predefined list full, long, medium, or short represented by date, time, or datetime. Instead, they are an open-ended list of patterns containing only date field information, and in a canonical order. <plus the examples>"?

About the date field link, it points to a table containing all the available CLDR patterns, its descriptions and examples. Do you think we should replicate that in here?

> * `pattern` is warned against - maybe we should reflect that in the name, e.g. rename to `rawPattern`? Or `machinePattern` to indicate that its not for human consumption? If yes, should create a separate issue for that

:+1:

> * Missing linebreak after "date" option - the others all have their description on a separate line

:+1:

> * "Their possible values are: full, long, medium, or short." - replace the "or" with "and"

:+1:

>* For the last section, "For improved performance on iterations"
>  * Does that really belong here? Seems like something that the `formatDate()` method should mention/warn about.
>  * If we keep this, make it executable: Replace or define `a` and `b` variables, replace or remove the `...`, do something with the formatted array.

I suggest we keep this piece of information for the reasons below. I'm ok making the code less pseudo. The idea of `...` is to demonstrate that this is a large Array. Should we add more real elements there? Any suggestion for the a and b dates?

Previously, we had a page for each `dateFormatter()` and `formatDate()` methods. There were too many duplicate information on both pages. This was also true for the other alias methods (e.g., `numberFormatter()` and `formatNumber()`, etc). In order to clarify and simplify that (+ make maintenance simpler), we have the full description in one page.

Although it seems obvious to us first creating the formatter and afterwards reusing it on each iteration, users could perform both steps inside the iteration nullifying any performance benefit of it. So, I still think it's good to point it out.

**Comment by jzaefferer** [comment]
> The first argument is not "skeleton". But, it can be.

Is that actually worth the ambiguity? Maybe we should just drop this argument-style and always require options with a specific property. It adds very little overhead in usage, removes ambiguity, might simplify the code and certainly simplifies the documentation. Though since there are no examples using this style, there are none to remove...

> Is the very little description you are referring to the 

Yes, and that's pretty slim for anyone not familiar with CLDR skeletons - and I'm assuming that will be the majority of users new to Globalize, since those don't exist in Moment or many other APIs (for example I've never seen them in any of the date/time APIs in Java that I've worked with).

> Do you think we should replicate that in here?

I'm not sure about that. Now that we have the example table, we may not need that. But I'd like to see a bit more introduction to skeletons, which then refers to the external page for details, along with the examples below.

> machinePattern

I vote for this, its a bit more obvious then `rawPattern`.

> Although it seems obvious to us first creating the formatter and afterwards reusing it on each iteration, users could perform both steps inside the iteration nullifying any performance benefit of it. So, I still think it's good to point it out.

Okay, that makes sense. So let's make the example runnable. A comment can indicate that the array could be very large.

**Comment by dmethvin** [comment]
> The first argument can be either a skeleton, any preset (date, time, or datetime), or a raw pattern. The name pattern should reflect it. I'm sure there's a better name for this argument. Any ideas?

I know jQuery core has a bunch of this kind of parameter hockey but it's not as clear to read or document, it requires explicit logic to sniff argument types, and it also fights against the new ES6 argument destructuring syntax. Removing the string signature sounds like a good idea.

**Comment by rxaviers** [comment]
About the first argument...

One additional alternative is to make it more similar to Ecma-402 API, which has this sort of input coming from `options`. In other words, we would drop the first argument by making it optional, which implies having a default datetime format (Ecma-402 uses `numeric` year, month, and day as default, e.g., `"3/18/2015"`). This way, we solve the first argument name problem (currently, it is confusing). In the future, we'll be able to extend `options` to accept the verbose pattern names (e.g., `{ weekday: "narrow" }`) similar to Ecma-402 as well.

**Comment by jzaefferer** [comment]
So we drop the `String` signature completely, while making the `Options` signature optional, with some sane default? That sounds good to me. Should be easier to document, implement and use.

I can't yet tell what the default should be, though at this point we should probably create another ticket for the API change.

**Comment by rxaviers** [comment]
Correct, Jörn. Created #425.

**Comment by jzaefferer** [comment]
Also need an issue to rename `pattern` option to `machinePattern` (or similar)

**Comment by rxaviers** [comment]
`pattern` has been renamed. Instead of `machinePattern` it became `raw`. So, I'm closing this issue.
