### ISSUE TITLE
Json cldr file not available

### ISSUE THREAD

**Issue by sebrojas14** [jquery/globalize#428]
From the link provide in https://github.com/jquery/globalize/blob/master/doc/cldr.md I got this error: The requested URL /Public/cldr/27.0.1/json.zip was not found on this server.

**Comment by rxaviers** [comment]
Documentation needs update.

CLDR has changed how to distribute its JSON files on 27. Now, you can download the data at https://github.com/unicode-cldr/cldr-json (more information [here](http://cldr.unicode.org/development/development-process/design-proposals/json-packaging)).

Having said that, note you can still use `cldr-data` just fine to download CLDR 27.

**Comment by sebrojas14** [comment]
Sorry, I think i couldn-t get to download the json data, can you explain it more? thank you

**Comment by Mottie** [comment]
This issue was opened because the links on that page are broken...

![2015-05-02 13_04_20-globalize_cldr md at master jquery_globalize](https://cloud.githubusercontent.com/assets/136959/7442203/b61e411e-f0cc-11e4-9614-5c70b002b3a3.png)

the files have been renamed, so it might be better to just change the links to point to http://www.unicode.org/Public/cldr/ so the page doesn't need to get updated all the time.

**Comment by rxaviers** [comment]
Please, see the change in https://github.com/rxaviers/cldrjs/pull/28/files. We need a similar change in here. Does it clarify?
