### ISSUE TITLE
Why globalize NuGet package does not include likelySubtags.json?

### ISSUE THREAD

**Issue by leniel** [jquery/globalize#507]
Without this file I get

```
Uncaught Error: E_MISSING_CLDR: Missing required CLDR content `supplemental/likelySubtags
```

when trying to set a `locale`.

I thought it would be included in the package automatically.

**Comment by rxaviers** [comment]
Hi @leniel, thanks for submitting this issue. Globalize itself doesn't include CLDR data. Please, read on https://github.com/jquery/globalize#where-does-the-data-come-from.

If you think there's anything we could do to make this information more clear, let me know and I'll be happy to reopen this issue.

Thanks

**Comment by leniel** [comment]
Hi @rxaviers ... I tried to execute the command:

```
npm install cldr-data
```

but it did not install... can you please tell me what's the problem by looking the the `npm-debug.log` file?
https://gist.github.com/leniel/22f2efda33175020047a

It tells it can be an error with the package itself. I'm not sure.

By the way... I used the old jQuery Globalize and it was much simpler. Now with this new version things are a bit difficult to start. :)

**Comment by johnnyreilly** [comment]
Hi @leniel,

If it helps you could take a look at my blog post that walks through the upgrade path from old Globalize to new Globalize. Best of luck!

http://blog.icanmakethiswork.io/2015/07/upgrading-to-globalize-1x-for-dummies.html

**Comment by rxaviers** [comment]
@leniel let's continue to investigate what's wrong with your npm installation in https://github.com/rxaviers/cldr-data-npm/issues/19.

About your 1.x experience, can you give me a short description of your use case? Are you using it on a web application, or on backend on Node.js? If web application, do you use any tools to generate the final minified bundles for your application?

**Comment by leniel** [comment]
Well... I have an ASP.NET MVC 5 app using .NET Framework 4.6. I currently use NuGet as package manager. I installed the Globalize Nuget package which pulled the cldr package as well as a dependency. That's fine but then I got the problem about it not finding the cldr-data `likelySubtags.json`.

With ASP.NET MVC I right now using the default bundling that comes with it like this:

```
 // jQuery Globalize
 bundles.Add(new ScriptBundle("~/bundles/globalize").Include(
                                         "~/Scripts/cldr.js",
                                         "~/Scripts/cldr/event.js",
                                         "~/Scripts/cldr/supplemental.js",
                                         "~/Scripts/globalize.js",
                                         "~/Scripts/globalize/number.js",
                                         "~/Scripts/globalize/plural.js",
                                         "~/Scripts/globalize/currency.js",
                                         "~/Scripts/globalize/date.js"));
```

but again... I'm not sure how to get the cldr-data files and include in my project. It would be awesome if there was a NuGet package for that too. :)

That's why I tried to run the npm command but it failed.

I then tried with bower hehehe following the directions that @johnnyreilly gave in his great post. Guess what: if fails with:

```
bower                                      postinstall node ./node_modules/cldr-data-downloader/bin/download.js -i bower_components/cldr-data/index.json -o bower_components/cldr-data/
bower                                          ECMDERR Failed to execute "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\node.CMD ./node_modules/cldr-data-downloader/bin/download.js -i bower_components/cldr-data/index.json -o bower_components/cldr-data/", exit code of #8
```

**Comment by CristianEriomencoRIT** [comment]
@leniel Its actually interesting that before using Globalize you need to hookup a whole environment with dependencies. 

Not everyone is using NPM as package manager, if every library would ask for its own package manager it would end up needing a Manager for Package Managers. 

I would highly appreciate a clear plain javascript way of setting up Globalize with remote CLDR data, as the current javascript example uses hardcoded data from one side, but from another it says that you should hardcode it because it defeats the point, and of course doesn't provide with an example of accomplishing that in a non npm, amd, requirejs whatever way.

Something like:

`var desiredLanguage = "en-GB";
var cldrData = $.get("https://hellknowswhat.url/"+desiredLanguage+"/data.json");

// Load data into Globalize
Globalize.load(cldrData);

// Instantiate globalize
Globalize.locale(desiredLanguage);`

Don't replicate IVR's when calling government services, KISS.

**Comment by rxaviers** [comment]
How do I get CLDR data? https://github.com/jquery/globalize/blob/master/doc/cldr.md

The thing about CLDR is that it's JSON data files. Globalize can interpret it during runtime, or you can precompile it all at build time and serve precompiled JS files (no JSON) via globalize-compiler. Globalize doesn't embed these JSON data within its modules because of two problems: (a) CLDR changes quickly than Globalize, so embedding would cause serving outdated content, (b) Globalize would embed a bunch of stuff you don't necessarily need in your app (it'd cause your app an awful load performance).

More about globalize-compiler can be found at:
- https://github.com/jquery/globalize/tree/master/examples/globalize-compiler#running-the-example
- https://github.com/jquery-support/globalize-compiler#README

What's my suggestion?

In your application, use Globalize as you don't need to load any CLDR. On development, let a helper tooling load the JSON for your dynamically. On production, let a helper tooling build the precompiled files, so you can bundle the smallest and fastest JS files in your produciton. Sounds crazy? It's exactly what this example do:

- https://github.com/jquery/globalize/tree/master/examples/app-npm-webpack

**Comment by CodeDog451** [comment]
Everyone is just going back to 0.1.3 since it works out of the box.

**Comment by trueqbit** [comment]
I am not going back to 0.1.3, but I think it would be helpful to have the CLDR json data available via CDN (github isn't one). Right now it's not even possible to write showcase examples e.g. on jsfiddle.net

**Comment by rxaviers** [comment]
Hi @TrejGun, not an answer, but this may be of your interest https://github.com/cdnjs/cdnjs/issues/10160

**Comment by rxaviers** [comment]
PS: I just noticed you found this link already :)
