### ISSUE TITLE
Change locale

### ISSUE THREAD

**Issue by ivan-kleshnin** [jquery/globalize#511]
Funny thing, but I can't change locale. 
Seems it should require `Globalize.locale(xxx);` to set it globally, but:

```js
console.log(Globalize.formatDate(new Date()));
Globalize.locale("ru");
console.log(Globalize.formatDate(new Date())); // Uncaught TypeError: this.dateFormatter(...) is not a function
```

I use Webpack + NMP example, production mode. Does it require `.load` or something? 
No examples are available and massive time is required to dig through that tons of code.

**Comment by rxaviers** [comment]
Hi Ivan,

Pretty simple. On the example's `webpack-config.js`, change `developmentLocale` or `supportedLocales` accordingly. You don't even need to use `Globalize.locale()` yourself, but this is also taken care automatically. `developmentLocale` will set the default locale for your development mode. `supportedLocales` will be the generated final bundles.

If you are trying to accomplish something else, please give me more details.

**Comment by ivan-kleshnin** [comment]
Thank you. Yes, you missed that I asked about production mode :wink:

> I use Webpack + NMP example, production mode.

**Comment by rxaviers** [comment]
Well, on production mode after running `npm run build`, it will be generated files in `./dist`. Edit `index.html` and make sure you are using the generated bundle for Russian. For example:

```diff
-<!-- <script src="i18n/ru.f89ee804cc2487764b00.js"></script> -->
+<script src="i18n/ru.f89ee804cc2487764b00.js"></script>
```

If you are using multiple language bundles, you can use `Globalize.locale()` dynamically in your code to switch between the ones you have loaded.

Did it help? Please, just let me know how it goes for you.

**Comment by ivan-kleshnin** [comment]
> If you are using multiple language bundles, you can use Globalize.locale() dynamically in your code to switch between the ones you have loaded.

Ok, then why I may get the error described in my first post. There was a comment in 3-rd line.
I had to make it more visible, sorry.

**Uncaught TypeError: this.dateFormatter(...) is not a function**

**Comment by rxaviers** [comment]
@ivan-kleshnin can you create a http://gist.github.com/ with the built files and your customization? I see you mentioning the error. But, I cannot reproduce it.

**Comment by ivan-kleshnin** [comment]
The thing is, I just took **Globalize/examples/app-npm-webpack** repo and add two lines
```js
Globalize.locale("ru");
console.log(Globalize.formatDate(new Date())); 
```
in `app/index.js` to get this exception.

Here is a demo video: https://drive.google.com/file/d/0B9bW0B92XgnAdHJ6dGtmWWZ0Wmc/view

**Comment by rxaviers** [comment]
**The easy way**

If you want to develop using the Russian locale, on webpack-config.js set `developmentLocale: "ru"`.

![video](https://cloud.githubusercontent.com/assets/967155/10145855/095a8ece-65fc-11e5-8266-1364b4141979.gif)

If you want to distribute the built bundles in the Russian locale, simply remove all `<script src="i18n/*"></script>` except for the Russian one `<script src="i18n/ru.*.js"></script>`.

![out](https://cloud.githubusercontent.com/assets/967155/10146575/100de7da-6600-11e5-883a-b7e73c73c51d.gif)

**The hard way**

If for some reason you want to set the locale using `Globalize.locale(locale)` yourself, you need to handle the CLDR loading yourself too. In order to do so, in webpack-config.js set the [globalize webpack](https://github.com/rxaviers/globalize-webpack-plugin) `cldr` option and pass the CLDR content for the Russian locale similar to [this code](https://github.com/rxaviers/globalize-webpack-plugin/blob/8e71f28de4a6e4385c15cc61cd7020d7cf7343fb/util.js#L9-L11). Please, just let me know if you need additional details here.

**Comment by rxaviers** [comment]
Feel free to reopen on any further questions.

**Comment by kaanilkyaz** [comment]
Hello there, I have the same issue but I want to use turkish language. I changed it with developmentLocale = "tr", still I get the same error.
