### ISSUE TITLE
Files with specific cultures

### ISSUE THREAD

**Issue by cezarypiatek** [jquery/globalize#615]
Where can I find files with specific cultures? I'm looking for en-GB culture file.

**Comment by rxaviers** [comment]
In previous Globalize 0.x, the project use to ship culture bundles, but the main problem with that was shipping outdated i18n data. Therefore, this is no longer done in Globalize 1.x. Instead, you can load the data directly from any [CLDR source](https://github.com/jquery/globalize/blob/master/doc/cldr.md).

That's what you need for `en-GB`: 

   npm install globalize cldr-data

```js
var Globalize = require( "globalize" );
Globalize.load( require( "cldr-data" ).entireSupplemental() );
Globalize.load( require( "cldr-data" ).entireMainFor( "en-GB"  ) );

Globalize("en-GB").formatDate(new Date());
// > '24/05/2016'
```

If you are using Globalize in a web application and you use webpack to bundle your files, take a look at this demo: https://github.com/jquery/globalize/tree/master/examples/app-npm-webpack. Here, you don't even need to worry about loading CLDR data, because Globalize webpack plugin takes care of that for you.

**Comment by rxaviers** [comment]
Feel free to make additional comments if you need further assistance.

**Comment by cezarypiatek** [comment]
@rxaviers  Thank you for your help but I'm still a little bit confused. I'm not using any of these modern js package managers. I need to manually add a file with specific culture to my project. I'm not sure which one should I download from CLDR source. Could you point me the right one?

**Comment by rxaviers** [comment]
Sure, the required i18n data depends on the use you make of Globalize. Information can be found here https://github.com/jquery/globalize/#2-cldr-content, including a web page to assist you in your question.

Let's continue discussing if you find any issues in the documentation. Otherwise, we should make it a [StackOverflow question](http://stackoverflow.com/tags/javascript-globalize).
